sonata_admin:
    title: 'Green World'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        dashboard: 'admin/dashboard_custom.html.twig'
        user_block: 'admin/user_block_custom.html.twig'
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
