admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /user
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /user
    prefix: /admin
